/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanTallyRouteImport } from './routes/scan-tally'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShipmentsPickedByRiderRouteImport } from './routes/shipments.picked-by-rider'
import { Route as ShipmentsInscanBagRouteImport } from './routes/shipments.inscan-bag'

const ScanTallyRoute = ScanTallyRouteImport.update({
  id: '/scan-tally',
  path: '/scan-tally',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsPickedByRiderRoute = ShipmentsPickedByRiderRouteImport.update({
  id: '/shipments/picked-by-rider',
  path: '/shipments/picked-by-rider',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsInscanBagRoute = ShipmentsInscanBagRouteImport.update({
  id: '/shipments/inscan-bag',
  path: '/shipments/inscan-bag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scan-tally': typeof ScanTallyRoute
  '/shipments/inscan-bag': typeof ShipmentsInscanBagRoute
  '/shipments/picked-by-rider': typeof ShipmentsPickedByRiderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scan-tally': typeof ScanTallyRoute
  '/shipments/inscan-bag': typeof ShipmentsInscanBagRoute
  '/shipments/picked-by-rider': typeof ShipmentsPickedByRiderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scan-tally': typeof ScanTallyRoute
  '/shipments/inscan-bag': typeof ShipmentsInscanBagRoute
  '/shipments/picked-by-rider': typeof ShipmentsPickedByRiderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/scan-tally'
    | '/shipments/inscan-bag'
    | '/shipments/picked-by-rider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/scan-tally'
    | '/shipments/inscan-bag'
    | '/shipments/picked-by-rider'
  id:
    | '__root__'
    | '/'
    | '/scan-tally'
    | '/shipments/inscan-bag'
    | '/shipments/picked-by-rider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScanTallyRoute: typeof ScanTallyRoute
  ShipmentsInscanBagRoute: typeof ShipmentsInscanBagRoute
  ShipmentsPickedByRiderRoute: typeof ShipmentsPickedByRiderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan-tally': {
      id: '/scan-tally'
      path: '/scan-tally'
      fullPath: '/scan-tally'
      preLoaderRoute: typeof ScanTallyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/picked-by-rider': {
      id: '/shipments/picked-by-rider'
      path: '/shipments/picked-by-rider'
      fullPath: '/shipments/picked-by-rider'
      preLoaderRoute: typeof ShipmentsPickedByRiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/inscan-bag': {
      id: '/shipments/inscan-bag'
      path: '/shipments/inscan-bag'
      fullPath: '/shipments/inscan-bag'
      preLoaderRoute: typeof ShipmentsInscanBagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScanTallyRoute: ScanTallyRoute,
  ShipmentsInscanBagRoute: ShipmentsInscanBagRoute,
  ShipmentsPickedByRiderRoute: ShipmentsPickedByRiderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
